### ISSUE TITLE
Yellow path fails when uploading document

### ISSUE THREAD

**Issue by vidhyabhushanbahl** [camunda-consulting/showroom-customer-onboarding#18]
**Yello path files when uploading document**

2021-02-09 11:45:10.331 ERROR 10220 --- [nio-8080-exec-7] org.camunda.bpm.engine.context           : **ENGINE-16004 Exception while closing command context: Cannot correlate message 'MESSAGE_documentReceived': No process definition or execution matches the parameters

org.camunda.bpm.engine.MismatchingMessageCorrelationException: Cannot correlate message 'MESSAGE_documentReceived': No process definition or execution matches the parameters**
        at org.camunda.bpm.engine.impl.cmd.CorrelateMessageCmd.execute(CorrelateMessageCmd.java:88) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.cmd.CorrelateMessageCmd.execute(CorrelateMessageCmd.java:42) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at com.camunda.consulting.simulator.commandinterceptor.CreateFireEventJobCommandInterceptor.execute(CreateFireEventJobCommandInterceptor.java:30) ~[camunda-bpm-simulator-1.6.0.jar:1.6.0]
        at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:110) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:46) ~[camunda-engine-spring-7.14.0-ee.jar:7.14.0-ee]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:44) ~[camunda-engine-spring-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.interceptor.ProcessApplicationContextInterceptor.execute(ProcessApplicationContextInterceptor.java:70) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.interceptor.CommandCounterInterceptor.execute(CommandCounterInterceptor.java:35) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:33) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.MessageCorrelationBuilderImpl.execute(MessageCorrelationBuilderImpl.java:313) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at org.camunda.bpm.engine.impl.MessageCorrelationBuilderImpl.correlateWithResult(MessageCorrelationBuilderImpl.java:224) ~[camunda-engine-7.14.0-ee.jar:7.14.0-ee]
        at com.camunda.demo.customeronboarding.facade.ApplicationOnlineFacade.submitDocument(ApplicationOnlineFacade.java:68) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]

**Comment by vidhyabhushanbahl** [comment]
The issue was because a process missing to read the message from email service. Start the email service and it worked.
